# Copyright (c) 2016-2022 Martin Donath <martin.donath@squidfunk.com>

# Project information
site_name: Machine Learning
site_url: https://github.com/fralfaro/python_ml
site_author: Francisco Alfaro
site_description: Machine Learning - Python

# Repository
repo_name: fralfaro/python_ml
repo_url: https://github.com/fralfaro/python_ml
edit_uri: ''



# Markdown extensions
markdown_extensions:
  - attr_list
  - admonition
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tabbed

# Extra javascript
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Theme
theme:
  name: material
  language: es
  logo: images/logo_ml.png
  favicon: images/logo_fam.png
  features:
    - navigation.instant
    - navigation.top
    - content.code.annotate
    - search.suggest
    - search.highlight
  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: white
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: black
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fralfaro
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/fralfaro
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/faam/
    - icon: fontawesome/brands/kaggle
      link: https://www.kaggle.com/faamds
    - icon: fontawesome/brands/medium
      link: https://medium.com/@fralfaro
    - icon: fontawesome/solid/globe
      link: https://fralfaro.github.io/portfolio/

# Plugins
plugins:
  - mkdocs-jupyter:
      kernel_name: python3
  - search


# TOC
nav:
    - Home: index.md
    - Introducción:
        - introduction/01_intro.ipynb
        - introduction/011_concepts.ipynb
        - introduction/012_sklearn.ipynb
        - Feature Enginerring:
            - introduction/013_feature_engineering.ipynb
            - introduction/0131_variables.ipynb
            - introduction/0132_transform.ipynb
            - introduction/0133_pipelines.ipynb
        - introduction/014_model_validation.ipynb

